/*
  Copyright (c) 2018-2025, Microsoft Research, Daan Leijen
  
  This is free software; you can redistribute it and/or modify it 
  under the terms of the MIT license. 

  A copy of the license can be found in the file "LICENSE" at the root 
  of this distribution.
*/

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> mi_malloc(int size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>()
external ffi.Pointer<ffi.Void> mi_calloc(int count, int size);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void mi_free(ffi.Pointer<ffi.Void> p);
